---
- name: Testing andrewrothstein.matchbox
  hosts: all
  tasks:
    - name: Installing andrewrothstein.matchbox
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}'
    - name: Executing 'matchbox --version'
      ansible.builtin.command: /usr/local/bin/matchbox --version
      changed_when: false
      register: matchbox_test_output
    - name: Output from 'matchbox --version'
      ansible.builtin.debug:
        msg: '{{ matchbox_test_output.stdout }}'
