---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/matchbox --version
      register: matchbox_test_output
    - name: matchbox --version
      debug:
        msg: '{{ matchbox_test_output.stdout }}'
