---
- name: Installing andrewrothstein.unarchivedeps
  ansible.builtin.include_role:
    name: andrewrothstein.unarchivedeps
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Check for install in {{ matchbox_install_dir }}
  become: true
  become_user: root
  ansible.builtin.stat:
    path: '{{ matchbox_install_dir }}'
  changed_when: false
  register: matchbox_binary
- name: Downloading and installing matchbox
  when: not matchbox_binary.stat.exists
  block:
    - name: Downloading {{ matchbox_tgz_url }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ matchbox_tgz_url }}'
        dest: '{{ matchbox_tmp_tgz }}'
        checksum: '{{ matchbox_checksum }}'
        mode: '644'
    - name: Unarchiving {{ matchbox_tmp_tgz }} to {{ matchbox_install_parent_dir }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ matchbox_tmp_tgz }}'
        dest: '{{ matchbox_install_parent_dir }}'
        creates: '{{ matchbox_install_dir }}'
  always:
    - name: Rm {{ matchbox_tmp_tgz }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ matchbox_tmp_tgz }}'
        state: absent
- name: Linking {{ matchbox_link_dir }} to {{ matchbox_install_dir }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ matchbox_install_dir }}'
    dest: '{{ matchbox_link_dir }}'
    state: link

- name: Linking {{ matchbox_link }} to {{ matchbox_install_exe }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ matchbox_install_exe }}'
    dest: '{{ matchbox_link }}'
    state: link
