---
- include_role:
    name: andrewrothstein.unarchive-deps
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: check for install in {{ matchbox_install_dir }}
  become: yes
  become_user: root
  stat:
    path: '{{ matchbox_install_dir }}'
  changed_when: False
  register: matchbox_binary
- when: not matchbox_binary.stat.exists
  block:
    - name: downloading {{ matchbox_tgz_url }}
      become: yes
      become_user: root
      get_url:
        url: '{{ matchbox_tgz_url }}'
        dest: '{{ matchbox_tmp_tgz }}'
        checksum: '{{ matchbox_checksum }}'
        mode: 0644
    - name: unarchiving {{ matchbox_tmp_tgz }} to {{ matchbox_install_parent_dir }}
      become: yes
      become_user: root
      unarchive:
        remote_src: yes
        src: '{{ matchbox_tmp_tgz }}'
        dest: '{{ matchbox_install_parent_dir }}'
        creates: '{{ matchbox_install_dir }}'
  always:
    - name: rm {{ matchbox_tmp_tgz }}
      become: yes
      become_user: root
      file:
        path: '{{ matchbox_tmp_tgz }}'
        state: absent
- name: linking {{ matchbox_link_dir }} to {{ matchbox_install_dir }}
  become: yes
  become_user: root
  file:
    src: '{{ matchbox_install_dir }}'
    dest: '{{ matchbox_link_dir }}'
    state: link

- name: linking {{ matchbox_link }} to {{ matchbox_install_exe }}
  become: yes
  become_user: root
  file:
    src: '{{ matchbox_install_exe }}'
    dest: '{{ matchbox_link }}'
    state: link
